config/routes.rb
Rails.application.routes.draw do
  resources :product_images
  resources :products
  resources :categories
  devise_for :users
  
  resources :tests

root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'new-product-image/:cid', to: 'product_images#new', as: :add_new_product_image
  get 'product-image-list/:cid', to: 'product_images#index', as: :product_image_list

end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
end

app/controllers/product_images_controller.rb
class ProductImagesController < ApplicationController
  before_action :set_product_image, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:new, :index]


  # GET /product_images
  # GET /product_images.json
  def index
    @product_images = ProductImage.where(id: @product.id)
  end



  # GET /product_images/1
  # GET /product_images/1.json
  def show
  end

  # GET /product_images/new
  def new
    @product_image = ProductImage.new
  end

  # GET /product_images/1/edit
  def edit
  end

  # POST /product_images
  # POST /product_images.json
  def create
    @product_image = ProductImage.new(product_image_params)
if params[:product_image][:data]
      @product_image.data = params[:product_image][:data].read
      @product_image.file_name  = params[:product_image][:data].original_filename
      @product_image.mime_type = params[:product_image][:data].content_type
    end
    respond_to do |format|
      if @product_image.save
        format.html { redirect_to @product_image, notice: 'Product image was successfully created.' }
        format.json { render :show, status: :created, location: @product_image }
      else
        format.html { render :new }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_images/1
  # PATCH/PUT /product_images/1.json
  def update
    respond_to do |format|
      if @product_image.update(product_image_params)
        format.html { redirect_to @product_image, notice: 'Product image was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_image }
      else
        format.html { render :edit }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_images/1
  # DELETE /product_images/1.json
  def destroy
    @product_image.destroy
    respond_to do |format|
      format.html { redirect_to product_images_url, notice: 'Product image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_image
      @product_image = ProductImage.find(params[:id])
    end

   def set_product
	@product = Product.find(params[:cid])
   end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_image_params
      params.require(:product_image).permit(:product_id, :data, :file_name, :mime_type, :order_no)
    end
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/views/product_images/_form.html.erb
<%= simple_form_for(@product_image, :html => {:multipart => true}  ) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
	<% if @product_image.persisted? %>
	    <%= f.association :product %>
	<% else %>
    	    <%= f.association :product, selected: @product.id %>
	<% end %>

    <%= f.file_field :data %>

    <%= f.input :order_no %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/product_images/edit.html.erb
<h1>Editing Product Image</h1>

<%= link_to 'Show', @product_image %> |
<%= link_to 'Back', product_image_list_path(@product_image.product) %>
<%= render 'form', product_image: @product_image %>

app/views/product_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Images</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product Name</th>
      <th>Order no</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @product_images.each do |product_image| %>
      <tr>
        <td>        <% unless product_image.data.nil? %>
                <%= ('<img class="img-fluid"  style="width:100px;" src="data:product_image.mime_type;base64,%s">' % Base64.encode64(product_image.data)).html_safe %>
                <% end %></td>
        <td><%= product_image.product.title %></td>
        <td><%= product_image.order_no %></td>
        <td><%= link_to 'Show', product_image %></td>
        <td><%= link_to 'Edit', edit_product_image_path(product_image) %></td>
        <td><%= link_to 'Destroy', product_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Image', add_new_product_image_path(@product) %>

app/views/product_images/new.html.erb
<h1>New Product Image</h1>

<%= render 'form', product_image: @product_image %>

<%= link_to 'Back', product_image_list_path(@product) %>

app/views/product_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_image.product.title %>
</p>

<p>
  <strong>Order no:</strong>
  <%= @product_image.order_no %>
</p>
<%= link_to 'Edit', edit_product_image_path(@product_image) %> |

<%= link_to 'Back', product_image_list_path(@product_image.product) %>
<p>
        <% unless @product_image.data.nil? %>
                <%= ('<img class="img-fluid"   src="data:@employee.mime_type;base64,%s">' % Base64.encode64(@product_image.data)).html_safe %>
                <% end %>



</p>